# By default 5080 is exposed on the host network
version : '3.4'

services :
  antmediaserver :
    network_mode: host
    container_name : antmediaserver
    image : "fluential/antmediaserver:${ANTMEDIA_VERSION:-latest}"
    volumes :
      - datastore:/usr/local/antmedia
    restart : always
volumes :
  datastore : {}
